# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
   - 2.11.8

script: "sbt clean coverage test"
after_success: 
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  matrix:
    - CUSTOM_JDK="default"
    - CUSTOM_JDK="oraclejdk8"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     # On Linux, run with specific JDKs only.
     - os: linux
       env: CUSTOM_JDK="default"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi  
