# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
   - 2.11.8

script: "sbt clean coverage test"
after_success: 
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - env: OS=Linux
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - env: OS=OSX
      os: osx
      jdk: oraclejdk8
      
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
