sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
   - 2.12.6
   - 2.11.12

jdk:
  - oraclejdk8

script: "sbt -jvm-opts .travis.jvmopts clean coverage 'testOnly -- xonly timefactor 5' coverageReport"
after_success: 
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
